export const ThemeColorModes: ThemeColorModes = {
  light: {
    accentColor: '',
    accentTextColor: '',
    defaultIconColor: '',
    dividerColor: '',
    errorColor: '',
    placeholderColor: '',
    primaryColor: '',
    primaryTextColor: '',
    screenBGColor: '',
    statusBarColor: '',
  },
  dark: {
    accentColor: '',
    accentTextColor: '',
    defaultIconColor: '',
    dividerColor: '',
    errorColor: '',
    placeholderColor: '',
    primaryColor: '',
    primaryTextColor: '',
    screenBGColor: '',
    statusBarColor: '',
  },
};
